In [4]:
import numpy as np

In [5]:
L = [1, 2, 3]

In [6]:
A = np.array([1, 2, 3])

In [7]:
for elements in L:
    print(elements)

1
2
3


In [8]:
for elements in A:
    print(elements)

1
2
3


In [9]:
L.append(4)

In [10]:
L

[1, 2, 3, 4]

In [12]:
2 * A

array([2, 4, 6])

In [13]:
L2 = []
for elements in L:
    L2.append(elements + 3)

In [15]:
L2

[4, 5, 6, 7]

In [17]:
L2 = [elements + 3 for elements in L]
L2

[4, 5, 6, 7]

In [18]:
a = np.array([1,2])
b = np.array([3,4])

In [19]:
dot = 0
for e, f in zip(a, b):
    dot += e * f
dot

11

In [20]:
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [21]:
np.sum(a * b)

11

In [22]:
a * b 

array([3, 8])

In [23]:
(a * b).sum()

11

In [24]:
np.dot(a, b)

11

In [25]:
a.dot(b)

11

In [26]:
a @ b


11

# Matrices

In [27]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [28]:
L[0]

[1, 2]

In [29]:
L[0][1]

2

In [30]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [31]:
A[0, 1]

2

In [32]:
A[:,0]

array([1, 3])

In [33]:
A[:,1]

array([2, 4])

In [34]:
A.T

array([[1, 3],
       [2, 4]])

In [35]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [36]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [38]:
B.shape


(2, 3)

In [40]:
np.linalg.det(A)

-2.0000000000000004

In [41]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [42]:
np.linalg.inv(A).dot(A)

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [44]:
np.trace(A)

5

In [45]:
np.diag(A)

array([1, 4])

In [46]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [47]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [48]:
Lam, V = np.linalg.eig(A)

In [49]:
V[:,0] * Lam[0] == A @ V[:, 0]

array([ True, False])

In [50]:
V[:,0] * Lam[0], A @ V[:, 0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [51]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [52]:
np.allclose(V @ np.diag(Lam), A @ V)

True

# Generating Data

In [53]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [56]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.random.random()

0.2381187580697497

In [58]:
np.random.random((2,3))

array([[0.18233314, 0.16707212, 0.36477756],
       [0.95819243, 0.05382609, 0.00384187]])

In [59]:
np.random.randn(2,3)

array([[-1.20006406, -1.00304515, -0.01587862],
       [ 0.41331005,  0.76439499, -1.41031725]])

In [60]:
R = np.random.randn(10000)

In [61]:
R.mean()

-0.0040523690799264675

In [62]:
np.mean(R)

-0.0040523690799264675

In [63]:
R.var()

1.0006031180576065

In [64]:
R.std()

1.0003015135735858

In [65]:
np.cov(R)

array(1.00070319)

In [66]:
np.random.randint(0,10, size=(3,3))

array([[3, 0, 0],
       [0, 6, 3],
       [4, 4, 8]])

In [67]:
np.random.randint(0,100,6)

array([85, 26, 83, 95, 84, 52])

In [68]:
np.random.randint(0,100,6).reshape(3,2)

array([[19, 73],
       [30, 35],
       [95, 59]])

In [69]:
a = np.array([1,2,3])
b = 6
print( a * b)

[ 6 12 18]


In [71]:
a = [1, 2, 3,4]
b = 3
print(a * b)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


# Loading Data using Pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('sbux.csv')

In [5]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.head()

date    open    high     low   close   volume  Name
0  2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [8]:
df.head(10)

date    open    high     low   close    volume  Name
0  2013-02-08  27.920  28.325  27.920  28.185   7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070   5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130   8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915   7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775   8899188  SBUX
5  2013-02-15  27.805  27.850  27.085  27.170  18195730  SBUX
6  2013-02-19  27.180  27.305  27.010  27.225  11760912  SBUX
7  2013-02-20  27.300  27.420  26.590  26.655  12472506  SBUX
8  2013-02-21  26.535  26.820  26.260  26.675  13896450  SBUX
9  2013-02-22  26.850  27.105  26.640  27.085  11487316  SBUX

In [9]:
df.tail()

date    open   high    low  close    volume  Name
1254  2018-02-01  56.280  56.42  55.89  56.00  14690146  SBUX
1255  2018-02-02  55.900  56.32  55.70  55.77  15358909  SBUX
1256  2018-02-05  55.530  56.26  54.57  54.69  16059955  SBUX
1257  2018-02-06  53.685  56.06  53.56  55.61  17415065  SBUX
1258  2018-02-07  55.080  55.43  54.44  54.46  13927022  SBUX

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   date    1259 non-null   object 
 1   open    1259 non-null   float64
 2   high    1259 non-null   float64
 3   low     1259 non-null   float64
 4   close   1259 non-null   float64
 5   volume  1259 non-null   int64  
 6   Name    1259 non-null   object 
dtypes: float64(4), int64(1), object(2)
memory usage: 69.0+ KB


# Selecting Rows and Columns in DataFrame

In [11]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name'], dtype='object')

In [12]:
df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'name']

In [13]:
df.head()

date    open    high     low   close   volume  name
0  2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [15]:
df['open']

0       27.920
1       28.260
2       28.000
3       28.230
4       27.765
         ...  
1254    56.280
1255    55.900
1256    55.530
1257    53.685
1258    55.080
Name: open, Length: 1259, dtype: float64

In [16]:
df[['open', 'close']]

open   close
0     27.920  28.185
1     28.260  28.070
2     28.000  28.130
3     28.230  27.915
4     27.765  27.775
...      ...     ...
1254  56.280  56.000
1255  55.900  55.770
1256  55.530  54.690
1257  53.685  55.610
1258  55.080  54.460

[1259 rows x 2 columns]

In [17]:
type(df['open'])

pandas.core.series.Series

In [18]:
type(df[['open', 'close']])

pandas.core.frame.DataFrame

In [19]:
df.iloc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
name            SBUX
Name: 0, dtype: object

In [20]:
df2 = pd.read_csv('sbux.csv', index_col ='date')

In [21]:
df2.head()

open    high     low   close   volume  Name
date                                                     
2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [22]:
df2.loc['2013-02-12']

open         28.0
high       28.275
low        27.975
close       28.13
volume    8665592
Name         SBUX
Name: 2013-02-12, dtype: object

In [24]:
df3 = pd.read_csv('sbux.csv', index_col ='close')

In [25]:
df3.head()

date    open    high     low   volume  Name
close                                                    
28.185  2013-02-08  27.920  28.325  27.920  7146296  SBUX
28.070  2013-02-11  28.260  28.260  27.930  5457354  SBUX
28.130  2013-02-12  28.000  28.275  27.975  8665592  SBUX
27.915  2013-02-13  28.230  28.230  27.750  7022056  SBUX
27.775  2013-02-14  27.765  27.905  27.675  8899188  SBUX

In [26]:
df[df['open'] > 64]

date   open    high    low  close   volume  name
1087  2017-06-05  64.85  64.870  64.18  64.27  6809284  SBUX
1088  2017-06-06  64.22  64.350  64.05  64.16  5448439  SBUX
1089  2017-06-07  64.13  64.295  63.34  63.50  8364994  SBUX

In [27]:
df[df['name'] != 'SBUX']

Empty DataFrame
Columns: [date, open, high, low, close, volume, name]
Index: []

In [28]:
[df['name'] != 'SBUX']

[0       False
 1       False
 2       False
 3       False
 4       False
         ...  
 1254    False
 1255    False
 1256    False
 1257    False
 1258    False
 Name: name, Length: 1259, dtype: bool]

In [30]:
type(df['name'] != 'SBUX')

pandas.core.series.Series

In [31]:
import numpy as np

In [32]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
A [A % 2 == 0]

array([0, 2, 4, 6, 8])

In [34]:
type([A % 2 == 0])

list

In [35]:
A = df[['open', 'close']].values
A

array([[27.92 , 28.185],
       [28.26 , 28.07 ],
       [28.   , 28.13 ],
       ...,
       [55.53 , 54.69 ],
       [53.685, 55.61 ],
       [55.08 , 54.46 ]])

In [36]:
type(A)

numpy.ndarray

# The Apply() Function